### ISSUE TITLE
Error when trying to process locally

### ISSUE THREAD

**Issue by codezomb** [markkerzner/FreeEed#90]
Using the ova download from the website. (FreeEed4.3.0)

When trying to process a file locally (both my own, and the test files included) I get the following error.

```
ubuntu@ubuntu-VirtualBox:~/freeeed_complete_pack$ 172143 [AWT-EventQueue-0] TRACE org.freeeed.main.PlatformUtil  - Running command: rm -fr output/freeeed-output/1003/output/results
172150 [Thread-10] INFO  org.freeeed.main.ActionProcessing  - Processing project: Demo
Processing: local
FreeEed V4.3.0, build date: Mon May 05 10:14:06 CDT 2014
172160 [Thread-10] INFO  org.freeeed.main.MRFreeEedProcess  - Running Hadoop job
172160 [Thread-10] INFO  org.freeeed.main.MRFreeEedProcess  - Input project file = output/freeeed-output/1003/output//staging/inventory
172160 [Thread-10] INFO  org.freeeed.main.MRFreeEedProcess  - Output path = output/freeeed-output/1003/output//results
172161 [Thread-10] DEBUG org.freeeed.main.MRFreeEedProcess  - project.isEnvHadoop() = false 
172161 [Thread-10] DEBUG org.freeeed.main.MRFreeEedProcess  - Ready to run, inputPath = output/freeeed-output/1003/output//staging/inventory, outputPath = output/freeeed-output/1003/output//results
172161 [Thread-10] TRACE org.freeeed.main.MRFreeEedProcess  - Project
172162 [Thread-10] TRACE org.freeeed.main.MRFreeEedProcess  - create-pdf=true
culling=
custodian=ubuntu
field-separator=pipe
file-system=local
files-per-zip-staging=100
gigs-per-zip-staging=6.0
input=/home/ubuntu/Desktop/test.nsf
lucene_fs_index_enabled=false
metadata=all
new-project-name=New project
ocr_enabled=false
ocr_max_images_per_pdf=10
output-dir-hadoop=output/freeeed-output/1003/output//results
output_dir=test-output/output
preview=false
process-where=local
project-code=1003
project-file-name=test.project
project-file-path=/home/ubuntu/test.project
project-name=Demo
remove-system-files=false
run=
send_index_solr_enabled=false
skip=0
staging_dir=test-output/staging

172447 [Thread-11] TRACE org.freeeed.main.PlatformUtil  - Running command: readpst -V

172451 [Thread-11] TRACE org.freeeed.main.PlatformUtil  - Running command: wkhtmltopdf -V

172461 [Thread-11] INFO  org.freeeed.main.Map  - readpst (PST extraction): true
wkhtmltopdf (html to pdf printing): true
172462 [Thread-11] WARN  org.apache.hadoop.mapred.LocalJobRunner  - job_local_0003
java.lang.IllegalStateException: Error parsing line recent-projects=
	at org.freeeed.services.Settings.loadFromString(Settings.java:359)
	at org.freeeed.main.Map.setup(Map.java:130)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:142)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:370)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:212)
173382 [Thread-10] INFO  org.freeeed.main.ActionProcessing  - Staging done
```

**Comment by markkerzner** [comment]
More details needed

**Comment by markkerzner** [comment]
Some settings, fixed now
