### ISSUE TITLE
ArrayIndexOutOfBoundsException in KeyComparator

### ISSUE THREAD

**Issue by markkerzner** [markkerzner/FreeEed#97]
Mitigate or fix

3999527 [Thread-3] DEBUG org.freeeed.main.KeyComparator  - t1=830cce2d2368e92d29628f485b32398b, t2=830cce2d2368e92d29628f485b32398b
3999566 [Thread-3] WARN  org.apache.hadoop.mapred.LocalJobRunner  - job_local_0001
java.lang.ArrayIndexOutOfBoundsException: 1
            at org.freeeed.main.KeyComparator.compare(KeyComparator.java:44)
            at org.apache.hadoop.io.WritableComparator.compare(WritableComparator.java:106)
            at org.apache.hadoop.mapred.Merger$MergeQueue.lessThan(Merger.java:373)
            at org.apache.hadoop.util.PriorityQueue.downHeap(PriorityQueue.java:139)
            at org.apache.hadoop.util.PriorityQueue.adjustTop(PriorityQueue.java:103)
            at org.apache.hadoop.mapred.Merger$MergeQueue.adjustPriorityQueue(Merger.java:335)
            at org.apache.hadoop.mapred.Merger$MergeQueue.next(Merger.java:350)
            at org.apache.hadoop.mapred.Merger.writeFile(Merger.java:156)
            at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.mergeParts(MapTask.java:1706)
            at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.flush(MapTask.java:1323)
            at org.apache.hadoop.mapred.MapTask$NewOutputCollector.close(MapTask.java:699)
            at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:766)
            at org.apache.hadoop.mapred.MapTask.run(MapTask.java:370)
            at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:212)
4000098 [Thread-0] INFO  org.freeeed.main.ActionProcessing  - Processing done

**Comment by markkerzner** [comment]
Not reproducible
